"""Shell-facing support wiring extracted from board_consumer."""

from __future__ import annotations

import startupai_controller.consumer_resolution_support_wiring as _resolution_support_wiring

import startupai_controller.consumer_launch_runtime_support_wiring as _launch_runtime_support_wiring
import startupai_controller.consumer_runtime_support_wiring as _runtime_support_wiring

record_metric = _runtime_support_wiring.record_metric
clear_claim_suppression = _runtime_support_wiring.clear_claim_suppression
activate_claim_suppression = _runtime_support_wiring.activate_claim_suppression
default_admission_summary = _runtime_support_wiring.default_admission_summary
claim_suppression_state = _runtime_support_wiring.claim_suppression_state
maybe_activate_claim_suppression = (
    _runtime_support_wiring.maybe_activate_claim_suppression
)
queue_status_transition = _runtime_support_wiring.queue_status_transition
queue_verdict_marker = _runtime_support_wiring.queue_verdict_marker
load_admission_summary = _runtime_support_wiring.load_admission_summary
next_available_slot = _runtime_support_wiring.next_available_slot
session_retry_state = _runtime_support_wiring.session_retry_state
complete_session = _runtime_support_wiring.complete_session
hydrate_issue_context = _launch_runtime_support_wiring.hydrate_issue_context
snapshot_for_issue = _launch_runtime_support_wiring.snapshot_for_issue
list_repo_worktrees = _launch_runtime_support_wiring.list_repo_worktrees
worktree_is_clean = _launch_runtime_support_wiring.worktree_is_clean
worktree_ownership_is_safe = _launch_runtime_support_wiring.worktree_ownership_is_safe
update_board_snapshot_statuses = (
    _launch_runtime_support_wiring.update_board_snapshot_statuses
)
run_worker_cycle = _launch_runtime_support_wiring.run_worker_cycle
prepare_multi_worker_launch_context = (
    _launch_runtime_support_wiring.prepare_multi_worker_launch_context
)
submit_multi_worker_task = _launch_runtime_support_wiring.submit_multi_worker_task
dispatch_multi_worker_launches = (
    _launch_runtime_support_wiring.dispatch_multi_worker_launches
)
verify_resolution_payload = _resolution_support_wiring.verify_resolution_payload
resolution_evidence_payload = _resolution_support_wiring.resolution_evidence_payload
